name: C++ CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: C++ Build & Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install tools
      run: sudo apt-get update && sudo apt-get install -y build-essential cppcheck

    - name: Compile project
      run: g++ simple-calculator-balaban/simple-calculator-surname.cpp simple-calculator-balaban/calculator.cpp simple-calculator-balaban/input.cpp -o calculator

    - name: Compile tests
      run: g++ tests/test.cpp simple-calculator-balaban/calculator.cpp simple-calculator-balaban/input.cpp -o test

    - name: Run tests
      run: ./test

    - name: Static analysis
      run: cppcheck --enable=all --error-exitcode=1 simple-calculator-balaban/